spring:
  application:
    name: academy-quotes

server:
  port: 8081

hero:
  heroes:
    - "Мастер Чиф"
    - "Кратос"
    - "Солид Снейк"
    - "Гордон Фримен"
    - "Принцесса Пич"
    - "Геральт из Ривии"
    - "Джоэл"
    - "Лара Крофт"
    - "Линк"
    - "Капитан Шепард"
    - "Натан Дрейк"
    - "Артур Морган"
    - "Тралл"
    - "Леон С. Кеннеди"
    - "Скорпион"

quotes:
  base-url: http://quotes:8082/
  quotes-url: quote
